#!/bin/sh
python acrobot_multiagent.py 10
python acrobot_multiagent.py 20
python acrobot_multiagent.py 10
python acrobot_multiagent.py 20
python acrobot_multiagent.py 10
python acrobot_multiagent.py 20
python acrobot_multiagent.py 10
python acrobot_multiagent.py 20
python acrobot_multiagent.py 10
python acrobot_multiagent.py 20
python acrobot_multiagent.py 10
python acrobot_multiagent.py 20
python acrobot_multiagent.py 10
python acrobot_multiagent.py 20
python acrobot_multiagent.py 10
python acrobot_multiagent.py 20
python acrobot_multiagent.py 10
python acrobot_multiagent.py 20
python acrobot_multiagent.py 10
python acrobot_multiagent.py 20