#!/bin/sh
python cartPole_multistep.py 10
python cartPole_multistep.py 10
python cartPole_multistep.py 10
python cartPole_multistep.py 10
python cartPole_multistep.py 10
python cartPole_multistep.py 10
python cartPole_multistep.py 10
python cartPole_multistep.py 10
python cartPole_multistep.py 10
python cartPole_multistep.py 10
python cartPole_multistep.py 20
python cartPole_multistep.py 20
python cartPole_multistep.py 20
python cartPole_multistep.py 20
python cartPole_multistep.py 20
python cartPole_multistep.py 20
python cartPole_multistep.py 20
python cartPole_multistep.py 20
python cartPole_multistep.py 20
python cartPole_multistep.py 20
