#!/bin/sh
python lunarLander_multistep.py 3
python lunarLander_multistep.py 5
python lunarLander_multistep.py 3
python lunarLander_multistep.py 5
python lunarLander_multistep.py 3
python lunarLander_multistep.py 5
python lunarLander_multistep.py 3
python lunarLander_multistep.py 5
python lunarLander_multistep.py 3
python lunarLander_multistep.py 5
python lunarLander_multistep.py 3
python lunarLander_multistep.py 5
python lunarLander_multistep.py 3
python lunarLander_multistep.py 5
python lunarLander_multistep.py 3
python lunarLander_multistep.py 5
python lunarLander_multistep.py 3
python lunarLander_multistep.py 5
python lunarLander_multistep.py 3
python lunarLander_multistep.py 5
