#!/bin/sh
python lunarLander_multistep.py 10
python lunarLander_multistep.py 20
python lunarLander_multistep.py 10
python lunarLander_multistep.py 20
python lunarLander_multistep.py 10
python lunarLander_multistep.py 20
python lunarLander_multistep.py 10
python lunarLander_multistep.py 20
python lunarLander_multistep.py 10
python lunarLander_multistep.py 20
python lunarLander_multistep.py 10
python lunarLander_multistep.py 20
python lunarLander_multistep.py 10
python lunarLander_multistep.py 20
python lunarLander_multistep.py 10
python lunarLander_multistep.py 20
python lunarLander_multistep.py 10
python lunarLander_multistep.py 20
python lunarLander_multistep.py 10
python lunarLander_multistep.py 20